### ISSUE TITLE
update repo then add readme to codeception module

### ISSUE THREAD

**Issue by SignpostMarv** [SignpostMarv/note-to-self#15]
notes:

1) `composer require --dev --update-with-dependencies weirdan/codeception-psalm-module codeception/codeception codeception/module-cli`
2) ignore codeception setup guide
3) add files
codeception.yml
```yml
namespace: Namespace\For\Plugin\Tests
settings:
    shuffle: true
    lint: true
actor_suffix: Tester
paths:
    tests: path-to-codeception-tests
    output: path-to-codeception-tests/_output
    support: path-to-codeception-tests/_support
    data: path-to-codeception-tests/_data
    envs: path-to-codeception-tests/_envs
extensions:
    enabled:
        - Codeception\Extension\RunFailed
```
path-to-codeception-tests/acceptance.suite.yml
```yml
actor: AcceptanceTester
modules:
    enabled:
        - Cli
        - Filesystem
        - \Weirdan\Codeception\Psalm\Module
```
4) ./vendor/bin/codecept build -v
5) ./vendor/bin/codecept run -v
